fix: Lift export
sillsdev/SpeechAnalyzer pull request #16
Opened 2021-07-13 07:12 UTC by darcywong00

This addresses the last two items of #2 
> - [ ] Even when "Phonemic" is unchecked, it still gets exported as "Abkhazian"
>  - [ ] @sdysart mentioned "Pronunciations" (phonetic / phonemic) need to be exported as Lexeme Form (IPA)

Regarding the checkboxes, this PR verifies the corresponding checkboxes before exporting a particular field.

## Language List Changes
There's also some language list "optimizations" for the following fields in the dialog. (Rather than populate from the entire iso629.txt list)
* Phonetic and Phonemic are always "International Phonetic Alphabet (IPA)"
* Gloss English is always "English"

Speech Analyzer already treats "Ortho"  as the vernacular writing system. So the phonetic and phonemic fields will now build the tag off of "Ortho", adding `-fonipa-x-etic` and `-fonipa-x-emic` respectively.

![image](https://user-images.githubusercontent.com/7358010/125407015-ab8a9700-e3e3-11eb-8a18-0038f24ac0aa.png)

Also, the `BS_AUTOCHECKBOX` changes in `SA_DEU.rc` were an attempt to reduce the number of default checkboxes. But it turns out the code will still enable those checkboxes since the test project contains those fields (even though blank)

----

TODO before merging:
- [ ] Build an installer off of this and have users test the Lift export/import process

2021-07-13 07:42 UTC, megahirt requested changes
Most everything looks good to me.  I'd like to request a change with the combo box - I don't think it's necessary any more.  I don't know how much work it will be to remove the combo box control from the UI and replace it with a label.  If it's a lot of work or there are many unknowns, then your existing code will work well enough to ship out the fixes contained in this PR.  Well done!

2021-07-13 07:42 UTC, megahirt commented on Src/SA/DlgExportLift.cpp
> +    wstring ipa = L"International Phonetic Alphabet (IPA)";
Instead of hardcoding the combo box with a single list item, how about removing the combo box control all together and simply displaying the text string "International Phonetic Alphabet (IPA)" as a label?  The checkbox still needs to be there but with this change, the combo box has no utility and serves the confuse the user.

2021-07-13 07:42 UTC, megahirt commented on Src/SA/DlgExportLift.cpp
> +    ctlGlossList.AddString(english.c_str());
see comment below; consider removing the combo box control entirely and simply replace with a static text label.

2021-07-14 03:04 UTC, darcywong00 commented
>  how about removing the combo box control all together and simply displaying the text string "International Phonetic Alphabet (IPA)" as a label?

I've converted the combo boxes to text labels for Phonetic, Phonemic, and English Gloss

![new dialog](https://user-images.githubusercontent.com/7358010/125554469-5d2bc86d-c515-416a-8d22-7961410d6a5f.png)

2021-07-14 04:52 UTC, megahirt approved these changes
Great!  Look at all the lines of code you deleted - it's a win!

2021-07-14 05:24 UTC, darcywong00 commented
Gonna go ahead and merge this one. The TODO to build the installer for testing will be handled in a separate PR

2021-07-14 05:24 UTC, merged