fix: Disable File "Save As" for mp3 files
sillsdev/SpeechAnalyzer pull request #54
Opened 2021-11-11 01:13 UTC by darcywong00

Fixes #49 

This PR disables the "Save As" File menu option when the active waveform is an mp3 file.

@terrygibbs - should we also disable on other file formats?
* .wma

2021-11-16 01:11 UTC, darcywong00 commented
From @kgorham 

> @darcywong00 I tried your download link. Seemed to run fine. (uninstalled old SA and reinstalled new). As an improvement, I would suggest stealing some of the code that is in place already, and use the first part of the original filename for the new filename instead of using the .tmp filename. @terrygibbs can second that opinion or not...
> 
> ![image](https://user-images.githubusercontent.com/10772332/141876924-65538b0a-3888-4186-b42f-eae9a6cad58e.png)

2022-02-28 07:41 UTC, megahirt requested changes
Nice work @darcywong00 .  I agree with @kgorham 's suggested change and request those changes - see comment inline.

2022-02-28 07:41 UTC, megahirt commented on Src/SA/SA_View.cpp
> +			path = doc.GetConvertedWaveFilename().c_str();
I agree with @kgorham 's [suggestion ](https://github.com/sillsdev/SpeechAnalyzer/pull/54#issuecomment-969583285)to make the saved filePath be the original MP3 filepath except changed to wav file extension.

I don't know this code, but if we are dealing with a fully qualified filePath then I might recommend adding some helper functions e.g.

`FileUtils::ReplaceFilename(fullPath, newFilename)` - replaces the filename in `fullPath`
`FileUtils::GetFilename(fullPath)` - returns just the filename portion of the path including extension

2022-03-01 09:46 UTC, darcywong00 commented on Src/SA/SA_View.cpp
> +			path = doc.GetConvertedWaveFilename().c_str();
I can try to do this.  I'd have to copy the temporary working wav file into the same temp folder with the original filename, since the missing wav file caused the original crash.

2022-03-03 04:46 UTC, megahirt approved these changes
Thanks @darcywong00

2022-03-03 06:00 UTC, merged